@DovizApi_HostAddress = http://localhost:5054

### Yeni müşteri + Hesap Ek No 5001 TRY hesabı oluştur
POST {{DovizApi_HostAddress}}/api/v1/musteriler
Content-Type: application/json

{
  "ad": "Ahmet",
  "soyad": "Test",
  "subeKodu": "001",
  "baslangicTryBakiyesi": 10000
}

### 005 kurulum verisindeki 1 numaralı müşterinin hesapları
GET {{DovizApi_HostAddress}}/api/v1/musteriler/1/hesaplar
Accept: application/json

### Döviz ek hesabı aç
POST {{DovizApi_HostAddress}}/api/v1/musteriler/1/hesaplar
Content-Type: application/json

{
  "dovizKodu": "EUR"
}

### Döviz çevir
POST {{DovizApi_HostAddress}}/api/v1/doviz-cevir
Content-Type: application/json

{
  "musteriId": 1,
  "borcluHesapEkNo": 5002,
  "alacakliHesapEkNo": 5001,
  "odenecekDovizMiktari": 1000
}

### İşlemleri ve kaynak/hedef dövizleri getir
GET {{DovizApi_HostAddress}}/api/v1/doviz-islemleri-getir
Accept: application/json
